version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    container_name: go_app
    restart: on-failure
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - migrate
    env_file:
      - ./.env
    networks:
      - testify_internal
    volumes:
      - ./:/usr/local/src

  db:
    image: postgres:latest
    container_name: go_db
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - ./.env
    networks:
      - testify_internal

  migrate:
    build:
      context: .
      dockerfile: ./build/migrations/Dockerfile
    container_name: go_migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - testify_internal

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    container_name: swagger
    ports:
      - "8081:8080"
    volumes:
      - ./docs/oapi/api.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml
    depends_on:
      - app

networks:
  testify_internal:
    external: true
    name: testify_internal

volumes:
  postgres_data: