// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/SergeiGD/testify-profile/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockConfirmationRepository is an autogenerated mock type for the ConfirmationRepository type
type MockConfirmationRepository struct {
	mock.Mock
}

type MockConfirmationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfirmationRepository) EXPECT() *MockConfirmationRepository_Expecter {
	return &MockConfirmationRepository_Expecter{mock: &_m.Mock}
}

// ConfirmUser provides a mock function with given fields: ctx, userID
func (_m *MockConfirmationRepository) ConfirmUser(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfirmationRepository_ConfirmUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUser'
type MockConfirmationRepository_ConfirmUser_Call struct {
	*mock.Call
}

// ConfirmUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockConfirmationRepository_Expecter) ConfirmUser(ctx interface{}, userID interface{}) *MockConfirmationRepository_ConfirmUser_Call {
	return &MockConfirmationRepository_ConfirmUser_Call{Call: _e.mock.On("ConfirmUser", ctx, userID)}
}

func (_c *MockConfirmationRepository_ConfirmUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockConfirmationRepository_ConfirmUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConfirmationRepository_ConfirmUser_Call) Return(_a0 error) *MockConfirmationRepository_ConfirmUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfirmationRepository_ConfirmUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockConfirmationRepository_ConfirmUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, confirmation
func (_m *MockConfirmationRepository) Create(ctx context.Context, confirmation *models.RegistrationConfirmation) error {
	ret := _m.Called(ctx, confirmation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RegistrationConfirmation) error); ok {
		r0 = rf(ctx, confirmation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfirmationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConfirmationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmation *models.RegistrationConfirmation
func (_e *MockConfirmationRepository_Expecter) Create(ctx interface{}, confirmation interface{}) *MockConfirmationRepository_Create_Call {
	return &MockConfirmationRepository_Create_Call{Call: _e.mock.On("Create", ctx, confirmation)}
}

func (_c *MockConfirmationRepository_Create_Call) Run(run func(ctx context.Context, confirmation *models.RegistrationConfirmation)) *MockConfirmationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RegistrationConfirmation))
	})
	return _c
}

func (_c *MockConfirmationRepository_Create_Call) Return(_a0 error) *MockConfirmationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfirmationRepository_Create_Call) RunAndReturn(run func(context.Context, *models.RegistrationConfirmation) error) *MockConfirmationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockConfirmationRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfirmationRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockConfirmationRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockConfirmationRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockConfirmationRepository_DeleteByUserID_Call {
	return &MockConfirmationRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockConfirmationRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockConfirmationRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConfirmationRepository_DeleteByUserID_Call) Return(_a0 error) *MockConfirmationRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfirmationRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockConfirmationRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockConfirmationRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*models.RegistrationConfirmation, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *models.RegistrationConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RegistrationConfirmation, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RegistrationConfirmation); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RegistrationConfirmation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfirmationRepository_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type MockConfirmationRepository_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockConfirmationRepository_Expecter) FindByTokenHash(ctx interface{}, tokenHash interface{}) *MockConfirmationRepository_FindByTokenHash_Call {
	return &MockConfirmationRepository_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *MockConfirmationRepository_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockConfirmationRepository_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConfirmationRepository_FindByTokenHash_Call) Return(_a0 *models.RegistrationConfirmation, _a1 error) *MockConfirmationRepository_FindByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfirmationRepository_FindByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*models.RegistrationConfirmation, error)) *MockConfirmationRepository_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockConfirmationRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*models.RegistrationConfirmation, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *models.RegistrationConfirmation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.RegistrationConfirmation, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.RegistrationConfirmation); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RegistrationConfirmation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfirmationRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockConfirmationRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockConfirmationRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockConfirmationRepository_FindByUserID_Call {
	return &MockConfirmationRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockConfirmationRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockConfirmationRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConfirmationRepository_FindByUserID_Call) Return(_a0 *models.RegistrationConfirmation, _a1 error) *MockConfirmationRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfirmationRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.RegistrationConfirmation, error)) *MockConfirmationRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, confirmation
func (_m *MockConfirmationRepository) Update(ctx context.Context, confirmation *models.RegistrationConfirmation) error {
	ret := _m.Called(ctx, confirmation)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RegistrationConfirmation) error); ok {
		r0 = rf(ctx, confirmation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfirmationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockConfirmationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - confirmation *models.RegistrationConfirmation
func (_e *MockConfirmationRepository_Expecter) Update(ctx interface{}, confirmation interface{}) *MockConfirmationRepository_Update_Call {
	return &MockConfirmationRepository_Update_Call{Call: _e.mock.On("Update", ctx, confirmation)}
}

func (_c *MockConfirmationRepository_Update_Call) Run(run func(ctx context.Context, confirmation *models.RegistrationConfirmation)) *MockConfirmationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RegistrationConfirmation))
	})
	return _c
}

func (_c *MockConfirmationRepository_Update_Call) Return(_a0 error) *MockConfirmationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfirmationRepository_Update_Call) RunAndReturn(run func(context.Context, *models.RegistrationConfirmation) error) *MockConfirmationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfirmationRepository creates a new instance of MockConfirmationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfirmationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfirmationRepository {
	mock := &MockConfirmationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
