// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/SergeiGD/testify-profile/config"
	grpcapi "github.com/SergeiGD/testify-profile/internal/api/grpc"
	"github.com/SergeiGD/testify-profile/internal/adapter/postgres"
	"github.com/SergeiGD/testify-profile/internal/api/http"
	"github.com/SergeiGD/testify-profile/internal/app"
	"github.com/SergeiGD/testify-profile/internal/server/grpcserv"
	"github.com/SergeiGD/testify-profile/internal/server/httpserv"
	"github.com/SergeiGD/testify-profile/internal/services/clock"
	"github.com/SergeiGD/testify-profile/internal/services/password"
	"github.com/SergeiGD/testify-profile/internal/services/token"
	"github.com/SergeiGD/testify-profile/internal/usecases/auth"
	"github.com/SergeiGD/testify-profile/internal/usecases/profile"
	"github.com/SergeiGD/testify-profile/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg *config.Config) (*app.App, func(), error) {
	loggerLogger := logger.NewLogger(cfg)
	pool, cleanup, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	userRepository := postgres.NewUserRepository(pool)
	confirmationRepository := postgres.NewConfirmationRepository(pool)
	emailSender := ProvideEmailSender(cfg, loggerLogger)
	passwordHasher := password.NewPasswordHasher()
	tokenService := token.NewTokenService()
	linkBuilder := ProvideLinkBuilder(cfg)
	clockClock := clock.NewRealClock()
	registerUseCase := ProvideRegisterUseCase(userRepository, confirmationRepository, emailSender, passwordHasher, tokenService, linkBuilder, clockClock, cfg)
	privateKey, err := ProvideRSAPrivateKey(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publicKey, err := ProvideRSAPublicKey(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jwtService := ProvideJWTService(privateKey, publicKey, cfg)
	authUseCase := auth.NewAuthUseCase(userRepository, passwordHasher, jwtService)
	strictServerInterface := http.NewServerHandler(registerUseCase, authUseCase)
	httpServer := httpserv.NewHttpServer(cfg, loggerLogger, strictServerInterface)
	profileUseCase := profile.NewProfileUseCase(userRepository)
	profileHandler := grpcapi.NewProfileHandler(profileUseCase)
	grpcServer := grpcserv.NewGrpcServer(cfg, loggerLogger, profileHandler)
	appApp := app.NewApp(cfg, httpServer, grpcServer)
	return appApp, func() {
		cleanup()
	}, nil
}
