// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockEmailSender is an autogenerated mock type for the EmailSender type
type MockEmailSender struct {
	mock.Mock
}

type MockEmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailSender) EXPECT() *MockEmailSender_Expecter {
	return &MockEmailSender_Expecter{mock: &_m.Mock}
}

// SendConfirmationEmail provides a mock function with given fields: to, confirmationLink
func (_m *MockEmailSender) SendConfirmationEmail(to string, confirmationLink string) error {
	ret := _m.Called(to, confirmationLink)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(to, confirmationLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailSender_SendConfirmationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConfirmationEmail'
type MockEmailSender_SendConfirmationEmail_Call struct {
	*mock.Call
}

// SendConfirmationEmail is a helper method to define mock.On call
//   - to string
//   - confirmationLink string
func (_e *MockEmailSender_Expecter) SendConfirmationEmail(to interface{}, confirmationLink interface{}) *MockEmailSender_SendConfirmationEmail_Call {
	return &MockEmailSender_SendConfirmationEmail_Call{Call: _e.mock.On("SendConfirmationEmail", to, confirmationLink)}
}

func (_c *MockEmailSender_SendConfirmationEmail_Call) Run(run func(to string, confirmationLink string)) *MockEmailSender_SendConfirmationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockEmailSender_SendConfirmationEmail_Call) Return(_a0 error) *MockEmailSender_SendConfirmationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailSender_SendConfirmationEmail_Call) RunAndReturn(run func(string, string) error) *MockEmailSender_SendConfirmationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailSender creates a new instance of MockEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailSender {
	mock := &MockEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
